debug: true
mode: "test"
project:
  name: "gin_project"
ver: "v1"
mysql:
  user: "www"
  password: "123456"
  ip: "127.0.0.1"
  port: "3306"
  name: "gin_project"
  charset: "utf8"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 500
basicauth:
  username: "foo"
  password: "bar"
etcd:
  endpoints:
  - 127.0.0.1:2379
  timeout: 5
rabbitmq:
  username: "guest"
  password: "guest"
  ip: "127.0.0.1"
  port: "5672"
log:
  file_path: "/tmp/app.log"
